### ISSUE TITLE
Running the tutorial for 3_plasticity, I got the CUDA error:

### ISSUE THREAD

**Issue by lwy-599** [UCI-CARL/CARLsim6#15]
CUDA error at carlsim/kernel/src/gpu_module/snn_gpu_module.cu:328 code=13(cudaErrorInvalidSymbol) "cudaMemcpyToSymbol(loadBufferCount, &bufferCnt, sizeof(int), 0, cudaMemcpyHostToDevice)" 

How does asking for help solve this problem?

**Comment by larsnm** [comment]
CARLsim 6 can generate CUDA device code optimized for distinct GPUs. 
This error can occur if the CMake parameter CARLSIM_CUDA_GENCODE was set wrong or for a differnt GPU. For instance, if the code generation was set for a  GTX Titan XP by "-gencode arch=compute_61,code=sm_61" and than executed on a RTX 3090 without setting and rebuilding with "-gencode arch=compute_86,code=sm_86". 

Hint: CARLSIM_CUDA_GENCODE is not mandatory and can be left empty in order to generate code  for all devices supported by the used CUDA version.
